/**
 * The security headers — the single definition.
 *
 * Two response paths exist and neither one covers the other:
 *
 *   · Static pages (/, /install, /rules, /research/compiler, /news, /privacy,
 *     CSS, images) are served by Cloudflare's static-asset layer, which never
 *     starts the Worker. Those get headers from the generated public/_headers.
 *   · The /go/* redirects and 404 are generated by worker/index.ts. Cloudflare
 *     documents that _headers does NOT apply to Worker-generated responses, so
 *     the Worker attaches them itself.
 *
 * Writing the table twice would let the two halves drift and nothing would
 * notice, because each path is exercised by different requests. So it is
 * written here once: scripts/site-gen-headers.mjs renders public/_headers from
 * this file, worker/index.ts imports it directly, and site-copy-lint's --dist
 * mode (rule R7) checks that the built _headers still contains every key.
 */

/**
 * Applies to every response the site produces, from either path.
 *
 * The CSP is unusually tight because the site was built to make it true rather
 * than to survive it: no web fonts (system-ui / ui-monospace only), no client
 * JavaScript (Astro static output, <details> for the menu), no third-party
 * anything, no forms. 'unsafe-inline' appears nowhere, and does not need to.
 */
export const BASE_HEADERS: Record<string, string> = {
  'Content-Security-Policy': [
    "default-src 'self'",
    "script-src 'none'",
    "style-src 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'none'",
    "frame-ancestors 'none'",
    "base-uri 'none'",
    "form-action 'none'",
  ].join('; '),
  'X-Content-Type-Options': 'nosniff',
  // Nothing downstream of this site should learn which page a visitor came
  // from — including the four stores they get redirected to.
  'Referrer-Policy': 'no-referrer',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
  // Redundant with frame-ancestors 'none' above, kept for implementations that
  // predate CSP Level 2.
  'X-Frame-Options': 'DENY',
};

/**
 * Added to the /go/* redirects only.
 *
 * Both entries protect the click count rather than the visitor. `noindex` keeps
 * the redirect URLs out of search results, where a visitor could land on one
 * without passing through /install. `no-store` keeps the browser from serving
 * the redirect from cache, which would mean the second click never reaches the
 * Worker at all — the same reason the redirect is a 302 and not a 301.
 */
export const GO_HEADERS: Record<string, string> = {
  'X-Robots-Tag': 'noindex',
  'Cache-Control': 'no-store',
};

/**
 * Enabled once a custom domain exists. Declaring HSTS while the site runs on a
 * *.workers.dev subdomain would pin a max-age onto a hostname shared with every
 * other Worker on that subdomain.
 */
export const HSTS_HEADER: Record<string, string> = {
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
};

/**
 * Whether a hostname is one we may pin with HSTS.
 *
 * `*.workers.dev` is shared with every other Worker on the platform, so an HSTS
 * header sent from there asks browsers to remember a policy for a name this
 * project does not own. Custom domains are the opposite: they are exactly what
 * HSTS is for.
 *
 * This is a function of the request, not of the build, and that distinction is
 * the bug it fixes. Both entry points used to call `staticHeaders()`, which read
 * `process.env.SITE_ORIGIN` — fine in Node, where the _headers file is
 * generated, and a ReferenceError inside the Workers runtime, which does not
 * define `process` unless `nodejs_compat` is enabled. The Worker caught the
 * throw and fell back to no-HSTS, which was right while the site had no domain
 * and would have stayed silently right forever afterwards: attaching a custom
 * domain would have switched HSTS on for the static pages and left every
 * Worker-generated response — all five redirects and the 404 — without it, with
 * nothing reporting the difference.
 */
export const hostAllowsHsts = (hostname: string): boolean =>
  hostname.length > 0 && !hostname.endsWith('.workers.dev') && hostname !== 'localhost';

/**
 * Headers for a response the STATIC layer serves. Called at build time from
 * Node by scripts/site-gen-headers.mjs, so reading the environment is safe here
 * and only here.
 */
export const staticHeaders = (): Record<string, string> => {
  // The origin has to pass the SAME test the Worker applies, not merely exist.
  //
  // An earlier version sent HSTS whenever SITE_ORIGIN was set to anything. That
  // is wrong the moment the site is deployed to *.workers.dev and told its own
  // URL — which is exactly the plan for the first release. The Worker would
  // refuse to pin that shared hostname while the static layer pinned it anyway,
  // so the six pages and the five redirects would disagree about a header whose
  // whole purpose is to be remembered by the browser. Neither half is allowed
  // to be the only one that knows the rule.
  const origin = typeof process !== 'undefined' ? process.env?.SITE_ORIGIN : undefined;
  let hsts = false;
  if (origin) {
    try {
      hsts = hostAllowsHsts(new URL(origin).hostname);
    } catch {
      // A SITE_ORIGIN that is not a URL is a configuration error, and the safe
      // reading of it is "no domain yet" rather than "pin whatever this is".
      hsts = false;
    }
  }
  return { ...BASE_HEADERS, ...(hsts ? HSTS_HEADER : {}) };
};

/**
 * Headers for a response the WORKER generates. `hostname` comes from the
 * request, so this never touches the environment and never throws in the
 * Workers runtime.
 */
export const workerHeaders = (hostname: string): Record<string, string> => ({
  ...BASE_HEADERS,
  ...(hostAllowsHsts(hostname) ? HSTS_HEADER : {}),
});

export const goHeaders = (hostname?: string): Record<string, string> => ({
  ...BASE_HEADERS,
  ...(hostname && hostAllowsHsts(hostname) ? HSTS_HEADER : {}),
  ...GO_HEADERS,
});
