#!/bin/bash
# Write the ladder specimen into the lab, on the side that produces it.
#
#   bash compiler/llvm-pass/tools/make-ladder.sh
#   IRCK_LADDER_LAB=/somewhere bash compiler/llvm-pass/tools/make-ladder.sh
#
# Same rule as tools/make-fixtures.sh: a fixture committed under compiler/ is a
# measurement input in the published tree, which the boundary guard fails on and
# which invariant 7d exists to prevent. Generating it keeps the bytes
# reproducible from the tracked tree without putting them in it -- this script IS
# the ladder, and it is reviewable as one.
#
# The ladder is one translation unit and is compiled with -c only, into a lab
# outside the repository, so it is never linked and never touches the objects of
# the build whose exposure is being read. The build's own bytes are identical
# whether or not this ran, by construction rather than by inspection.
#
# After emitting the file, this script prints the function names the file
# actually defines, read back out of the emitted bytes. run-ladder.sh checks its
# rung table against that list, which is the fence against the observer's third
# silent failure mode: a subject name that resolves to nothing gives rc 0, empty
# stderr, a non-empty log and a held control, with only the subject's rows
# missing -- a renamed function would otherwise be recorded as a reading rather
# than as a mistake. A list kept by hand beside the file can be right about a
# file that has changed, so the list is derived and not kept.
#
# The output is key=value on stdout, in the shape observe-config.sh's manifests
# already use:
#
#   ladder=<path to the emitted translation unit>
#   fn=<one defined function name>   (repeated)
set -u

LAB=${IRCK_LADDER_LAB:-$HOME/vg-lab/llvm-pass-ladder}
FX="$LAB/fixtures"
SRC="$FX/ladder/ladder.c"

mkdir -p "$FX/ladder"

cat > "$SRC" <<'FIXTURE_EOF'
/* The ladder: a graded specimen compiled under the build's own command
 * line, whose pattern of surviving rungs is the reading.
 *
 * Generated by tools/make-ladder.sh; never committed as a fixture.
 *
 * One translation unit, compiled with -c only, so nothing here is ever linked
 * and every opaque producer/consumer can stay an undefined extern.
 *
 * Buffer sizes are pairwise-distinct primes: the memory-object discriminator
 * decides LOST from NOT_APPLICABLE by an alloca size census, and two objects of
 * one size in a unit made a promoted buffer read as a deleted wipe.
 */

#include <string.h>
#include <stdio.h>

/* Opaque, by construction: declared here, defined nowhere, never linked. */
extern void vgl_fill(void *p, unsigned long n);
extern void vgl_use(const void *p, unsigned long n);
extern unsigned long vgl_len(void);
extern int vgl_cond(void);
extern double vgl_dbl(void);
extern void vgl_deny(void);

/* Spelling anchors. The asm label pins the callee name the IR must show, so a
 * control can hold one spelling while the subject's spelling is what moves. */
extern void *vgl_memset_lib(void *, int, unsigned long) __asm__("memset");
extern void *vgl_memset_chk(void *, int, unsigned long, unsigned long)
    __asm__("__memset_chk");
extern int vgl_printf_lib(const char *, ...) __asm__("printf");
extern int vgl_puts_lib(const char *) __asm__("puts");
extern int vgl_printf_chk(int, const char *, ...) __asm__("__printf_chk");

/* ---------------------------------------------------------------- wipe chain */

/* a0: nothing escapes, so the object itself can be promoted out of memory.
 * The rung that separates -O0 from everything above it. */
void vgl_a0(void) {
  unsigned char b[59];
  for (unsigned i = 0; i < 59; i++) b[i] = (unsigned char)i;
  memset(b, 0, sizeof b);
}

/* a1: escapes to an opaque consumer, then a wipe nobody reads. */
void vgl_a1(void) {
  unsigned char b[61];
  vgl_fill(b, sizeof b);
  vgl_use(b, sizeof b);
  memset(b, 0, sizeof b);
}

/* a1_twin: the same wipe, read afterwards. Not legally removable. */
void vgl_a1_twin(void) {
  unsigned char b[67];
  vgl_fill(b, sizeof b);
  memset(b, 0, sizeof b);
  vgl_use(b, sizeof b);
}

/* a2: the wipe written as a loop rather than as a call. */
void vgl_a2(void) {
  unsigned char b[71];
  vgl_fill(b, sizeof b);
  vgl_use(b, sizeof b);
  for (unsigned i = 0; i < 71; i++) b[i] = 0;
}

void vgl_a2_twin(void) {
  unsigned char b[73];
  vgl_fill(b, sizeof b);
  for (unsigned i = 0; i < 73; i++) b[i] = 0;
  vgl_use(b, sizeof b);
}

/* a3: the wipe behind a static helper, so inlining has to happen first. */
static void vgl_wipe3(void *p, unsigned long n) { memset(p, 0, n); }

void vgl_a3(void) {
  unsigned char b[79];
  vgl_fill(b, sizeof b);
  vgl_use(b, sizeof b);
  vgl_wipe3(b, sizeof b);
}

/* a3_twin wipes directly rather than through the helper. A control has to be
 * countable at EVERY checkpoint, and an effect behind a not-yet-inlined static
 * helper is not there at pre-opt-ir: the call in the unit is to the helper, and
 * the helper's name is not an effect symbol. Measured 2026-08-17 -- the helper
 * form read 0/1 and took the whole a3 rung out as a broken measurement. */
void vgl_a3_twin(void) {
  unsigned char b[83];
  vgl_fill(b, sizeof b);
  memset(b, 0, sizeof b);
  vgl_use(b, sizeof b);
}

/* -------------------------------------------------- wipe spelling discriminator
 *
 * Irremovable by construction (the zeros are read). What moves across exposures
 * is not whether the effect is there but what it is spelled as: the length is a
 * runtime value while the object size is known, which is the shape a fortifying
 * header rewrites.
 */
void vgl_b1(void) {
  unsigned char b[89];
  vgl_fill(b, sizeof b);
  memset(b, 0, vgl_len());
  vgl_use(b, sizeof b);
}

/* One control per spelling. Each pins its own callee name at every exposure. */
void vgl_ctl_intr(void) {
  unsigned char b[97];
  vgl_fill(b, sizeof b);
  __builtin_memset(b, 0, vgl_len());
  vgl_use(b, sizeof b);
}

__attribute__((no_builtin("memset"))) void vgl_ctl_lib(void) {
  unsigned char b[101];
  vgl_fill(b, sizeof b);
  vgl_memset_lib(b, 0, vgl_len());
  vgl_use(b, sizeof b);
}

void vgl_ctl_chk(void) {
  unsigned char b[103];
  vgl_fill(b, sizeof b);
  vgl_memset_chk(b, 0, vgl_len(), sizeof b);
  vgl_use(b, sizeof b);
}

/* --------------------------------------------------------------------- guards
 *
 * Scalar bodies with no arrays, so a stack-protector variant does not add a
 * canary branch: the live-branch gate counts branches per unit, not per call.
 */
/* Not `const`: a const initialiser is folded by the front end, so the branch
 * never reaches the IR at all and the rung reads ABSENT at every level,
 * discriminating nothing. Measured 2026-08-17. Written once and never again,
 * so the optimiser -- not the front end -- is the thing that decides it. */
static int vgl_zero = 0;

/* c1: a guard the optimiser can decide. The deny call goes with the branch. */
void vgl_c1(void) {
  if (vgl_zero) vgl_deny();
}

/* c1_twin: a guard on a value from outside the unit. Neither can be folded. */
void vgl_c1_twin(void) {
  if (vgl_cond()) vgl_deny();
}

/* c2: a NaN test. Only relaxed floating point can decide it. */
void vgl_c2(void) {
  double x = vgl_dbl();
  if (x != x) vgl_deny();
}

/* ------------------------------------------------ call-rewrite discriminator */

void vgl_d1(void) { printf("vgl\n"); }

void vgl_ctl_printf(void) { vgl_printf_lib("vgl %d\n", vgl_cond()); }

void vgl_ctl_puts(void) { vgl_puts_lib("vgl"); }

void vgl_ctl_printf_chk(void) { vgl_printf_chk(1, "vgl %d\n", vgl_cond()); }
FIXTURE_EOF

# A definition, not a declaration: the name is followed by a parameter list with
# no nested parentheses and then an opening brace, which every definition in the
# file above satisfies on one line. The declarations end in `;` and the call
# sites inside the bodies are followed by `;` or by another `)`, so neither can
# be mistaken for a definition here. The static helper is listed too -- it is a
# function this unit defines, and whether a rung may name it is run-ladder.sh's
# business, not this script's.
DEFINED=$(grep -oE '\bvgl_[A-Za-z0-9_]*[[:space:]]*\([^()]*\)[[:space:]]*\{' "$SRC" \
          | sed -E 's/[[:space:]]*\(.*$//' | sort -u)

# An empty list would let every rung check pass vacuously downstream, which is
# the failure this whole output exists to prevent, so it is refused here.
if [ -z "$DEFINED" ]; then
  echo "make-ladder.sh: no function definitions were found in $SRC" >&2
  exit 1
fi

echo "ladder=$SRC"
printf '%s\n' "$DEFINED" | sed 's/^/fn=/'
