// The Worker half of the site.
//
// WHY THERE IS A WORKER AT ALL
//
// Cloudflare's static-asset layer serves the six content pages without ever
// starting this script, and requests it answers are free and unlimited. So this
// file is not "the server"; it is the small remainder that static files cannot
// express. There are exactly four of those, and nothing else belongs here:
//
//   1. /go/<channel> — count the click, then redirect. A static file cannot
//      count, and counting is the site's primary KPI.
//   2. Any unmatched path — render the 404 page. The asset layer is configured
//      without `not_found_handling` precisely so these fall through to here.
//   3. The search-console verification files. These ARE static files in every
//      sense and would live in public/ on any other site; they are here because
//      the asset layer's `html_handling: "drop-trailing-slash"` answers a
//      request for `/x.html` with a 307 to `/x`, and a proof of ownership has
//      to be a 200 at the path the console was given. See ../src/shared/
//      verification.ts for the full argument and the token itself.
//   4. Security headers on all of the above. Cloudflare documents that the
//      `_headers` file is NOT applied to responses generated by Worker code, so
//      the two response paths have to attach the same table by different means:
//      static pages get public/_headers (rendered by
//      scripts/site-gen-headers.mjs), and everything below calls into
//      ../src/headers directly. Same source, two deliveries.
//
// WHAT THIS FILE DELIBERATELY DOES NOT DO
//
// It reads the request path and nothing else. Not a header, not the body, not
// the `cf` object that Cloudflare attaches with country and ASN. /privacy says
// this site does not store IP addresses, User-Agent, Referer or any visitor
// identifier — and the way that sentence is kept true is that the code never
// has those values in a variable in the first place. A promise not to store
// something you are holding is a policy; not holding it is a structure. Adding
// a fifth thing to the list above means re-reading /privacy in the same commit
// and editing it unless the new thing also reads only the path and stores
// nothing — which is why item 3 arrived without a /privacy change.
import { GO_TARGETS, isChannel, type Channel } from '../src/shared/links';
import { VERIFICATION_FILES, isVerificationPath } from '../src/shared/verification';
import { goHeaders, workerHeaders } from '../src/headers';

/**
 * The subset of Cloudflare's `Fetcher` this file uses.
 *
 * Declared structurally rather than imported from `@cloudflare/workers-types`
 * because the site carries no dependencies it does not need, and this is the
 * whole surface: one method, called once. `npm audit` on site/ is clean and
 * stays that way by not growing packages for type aliases.
 */
interface AssetFetcher {
  fetch(request: Request): Promise<Response>;
}

/**
 * The click counter, as an Analytics Engine dataset would present it.
 *
 * Optional on purpose. wrangler.jsonc has the `GO_CLICKS` binding commented
 * out, because nobody has confirmed in the Cloudflare dashboard that Analytics
 * Engine is available on this account's plan — the public documentation does
 * not state it. Until someone does, `env.GO_CLICKS` is `undefined` at runtime,
 * and the code below has to treat that as "do not count", never as an error.
 * The redirect is the user-visible half; the count is the operator's half. If
 * they ever disagree about whether to work, the redirect wins.
 */
interface ClickCounter {
  writeDataPoint(event: { indexes?: string[]; blobs?: string[]; doubles?: number[] }): void;
}

export interface Env {
  ASSETS?: AssetFetcher;
  GO_CLICKS?: ClickCounter;
}

/** The one prefix this Worker claims. Everything else is a 404. */
const GO_PREFIX = '/go/';

/** Where the 404 body comes from. Astro's build:format 'file' emits this name. */
const NOT_FOUND_ASSET = '/404.html';

/**
 * Security headers for a response this Worker generated, minus the /go/*
 * extras.
 *
 * This used to call `staticHeaders()` inside a try/catch. That function decided
 * whether to send HSTS by reading `process.env.SITE_ORIGIN`, and `process` is a
 * Node global that the Workers runtime does not define without `nodejs_compat`
 * — so the read was a ReferenceError in production while working perfectly
 * under vitest, the worst shape a bug can have. The catch returned the base
 * headers, which was the right answer while the site had no domain and would
 * have stayed silently right forever: attaching a custom domain would have
 * switched HSTS on for the static pages and left every response this file
 * generates without it.
 *
 * `workerHeaders()` decides from the request's hostname instead, so it never
 * touches the environment, cannot throw here, and starts sending HSTS by itself
 * on the day a real domain is attached.
 */

/**
 * Record one click on `channel`.
 *
 * The key is `go:<channel>:<YYYY-MM-DD>` in UTC, which is the entire record:
 * channel, day, and the fact that it happened once. Three fields, matching the
 * three /privacy commits to storing. UTC rather than local time because "local"
 * for a Worker means whichever colo answered, so a day boundary would move with
 * the visitor and the weekly deltas would not add up.
 *
 * Two failure modes are swallowed here and both are deliberate. A missing
 * binding means the dataset was never enabled; a throwing `writeDataPoint`
 * means the platform refused the write. Neither is a reason to fail a visitor's
 * click on the way to an extension store: the worst outcome of ignoring them is
 * an undercount in a number only the operator reads.
 */
function countClick(env: Env, channel: Channel): void {
  const counter = env.GO_CLICKS;
  if (!counter || typeof counter.writeDataPoint !== 'function') return;

  const day = new Date().toISOString().slice(0, 10);
  try {
    counter.writeDataPoint({
      indexes: [`go:${channel}:${day}`],
      blobs: [channel, day],
      doubles: [1],
    });
  } catch {
    // See above: counting never breaks redirecting.
  }
}

/**
 * The 404 body, taken from the built site so it looks like the rest of the
 * site rather than like a platform error page.
 *
 * A brand-new Request is issued instead of forwarding the caller's, which
 * drops every header the visitor sent before it can reach anything that might
 * log it. That is a side effect of the privacy rule at the top of this file,
 * and a welcome one.
 *
 * The plain-text fallback covers the two cases where the asset lookup cannot
 * produce a page: the binding is absent (local runs, tests), or the build
 * shipped without a 404 page. Returning Cloudflare's own error screen there
 * would be a worse answer — it carries none of the site's headers, which is the
 * one thing this function exists to guarantee.
 */
async function notFound(request: Request, env: Env): Promise<Response> {
  const headers = { ...workerHeaders(new URL(request.url).hostname) };

  if (env.ASSETS) {
    try {
      const assetUrl = new URL(NOT_FOUND_ASSET, request.url);
      const asset = await env.ASSETS.fetch(new Request(assetUrl.toString()));
      if (asset.ok) {
        return new Response(asset.body, {
          status: 404,
          headers: {
            ...headers,
            'Content-Type': asset.headers.get('Content-Type') ?? 'text/html; charset=utf-8',
          },
        });
      }
    } catch {
      // Fall through to the text body below.
    }
  }

  return new Response('Not found. Go to / for the VibeGuard site.\n', {
    status: 404,
    headers: { ...headers, 'Content-Type': 'text/plain; charset=utf-8' },
  });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // The only thing read from the request. `pathname` is already
    // percent-decoded-safe and query-free; the URL rules forbid query strings
    // on site links anyway, and /go/* would split its own count if it allowed
    // them, since /go/vscode?x=1 and /go/vscode are different cache entries.
    const path = new URL(request.url).pathname;

    if (path.startsWith(GO_PREFIX)) {
      // A single trailing slash is tolerated. The asset layer's
      // drop-trailing-slash only rewrites paths that match an asset, and /go/*
      // never matches one, so /go/vscode/ arrives here verbatim. Normalising it
      // keeps a stray slash in someone's blog post from becoming a 404, and it
      // folds into the same counter key rather than creating a second one.
      const candidate = path.slice(GO_PREFIX.length).replace(/\/$/, '');

      // An allowlist, not a pattern. `isChannel` is a lookup in the same table
      // that supplies the destination, so an unknown segment cannot produce a
      // redirect at all — which is what keeps this from being an open redirect
      // the day someone "generalises" it to /go/:anything.
      if (isChannel(candidate)) {
        countClick(env, candidate);
        return new Response(null, {
          status: 302,
          headers: {
            ...goHeaders(new URL(request.url).hostname),
            // 302, never 301. A permanent redirect gets cached by the browser
            // and the second click never reaches this code, so the number that
            // the whole counter exists to produce would quietly shrink.
            // Cache-Control: no-store, from goHeaders(), is the other half of
            // the same argument.
            Location: GO_TARGETS[candidate],
          },
        });
      }

      // Deliberately shares the 404 path with everything else. /go/evil is not
      // special-cased into some "unknown channel" response, because a distinct
      // response would confirm to a prober which segments exist.
    }

    // The ownership proofs. An exact-path lookup, never a prefix or a pattern:
    // the response is the token itself, so anything looser would hand a prober
    // the contents of a file they were supposed to have been given already.
    //
    // The body is the file byte for byte, with no trailing newline, because
    // Search Console compares the content it issued and this is that content.
    // The headers are the ones a page in public/ would have received from
    // _headers — nothing is added on top. In particular there is no
    // `X-Robots-Tag: noindex` here: robots.txt already names the six pages that
    // belong in an index and this is not one of them, and a directive aimed at
    // the crawler is not worth the risk of it being read by the verifier, which
    // is a different fetcher with undocumented behaviour on that header.
    if (isVerificationPath(path)) {
      return new Response(VERIFICATION_FILES[path], {
        status: 200,
        headers: {
          ...workerHeaders(new URL(request.url).hostname),
          'Content-Type': 'text/html; charset=utf-8',
        },
      });
    }

    return notFound(request, env);
  },
};
