// The decoder has exactly one job with two halves: say where a generated byte
// came from when the map really says so, and REFUSE — audibly, for the whole
// artefact — when it does not. The second half is the one under test here,
// because it is the half that decides whether an unattributable witness lands
// on NOT_OBSERVED or on a confident PRESENT.
//
// Every validity check below is a shape a real producer can emit or a
// mis-decode can reach. That is what makes them a runtime control rather than
// decoration, and it is the difference between these and the negative-control
// canary that used to live in `bundle.mjs`: that one could not fire.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  MAX_MAPPING_SEGMENTS,
  SPAN_ATTRIBUTION_CAP,
  coarseWidthAt,
  decodeSourceRegions,
  regionSourceAt,
  sourceIndexesCarrying,
} from '../src/source-map-regions.mjs';

const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Base64 VLQ, the encoding side.
 *
 * Deliberately written twice — here and in `cross-examine.test.mjs` — rather
 * than shared. A helper shared with the code under test proves nothing, and a
 * helper shared between two suites lets one wrong fix silence both.
 */
function vlq(n) {
  let v = n < 0 ? -n * 2 + 1 : n * 2;
  let out = '';
  do {
    let digit = v % 32;
    v = Math.floor(v / 32);
    if (v > 0) digit += 32;
    out += B64[digit];
  } while (v > 0);
  return out;
}

/** One generated line's worth of segments, from ABSOLUTE field values. */
function line(segments) {
  let col = 0;
  let src = 0;
  let origLine = 0;
  let origCol = 0;
  return segments
    .map((s) => {
      const out =
        s.length === 1
          ? vlq(s[0] - col)
          : vlq(s[0] - col) + vlq(s[1] - src) + vlq(s[2] - origLine) + vlq(s[3] - origCol);
      col = s[0];
      if (s.length > 1) {
        [, src, origLine, origCol] = s;
      }
      return out;
    })
    .join(',');
}

const mapOf = (mappings, contents = ['a\nb\nc', 'd\ne\nf']) => ({
  version: 3,
  sources: contents.map((_, i) => `src/${i}.js`),
  sourcesContent: contents,
  mappings,
});

// ── THE HAPPY PATH, SO THE REFUSALS BELOW ARE NOT VACUOUS ───────────────────

test('one segment per module gives one region per module', () => {
  const code = 'AAAAAAAAAA' + 'BBBBBBBBBB';
  const { regions, coarse } = decodeSourceRegions(code, mapOf(line([[0, 0, 0, 0], [10, 1, 0, 0]])));
  assert.deepEqual(regions, [
    { start: 0, end: 10, source: 0 },
    { start: 10, end: 20, source: 1 },
  ]);
  assert.deepEqual(coarse, []);
});

test('the last segment on a line runs to the end of that line, not into the next', () => {
  const code = 'AAAAA\nBBBBB';
  const { regions } = decodeSourceRegions(code, mapOf(`${line([[0, 0, 0, 0]])};${line([[0, 1, 0, 0]])}`));
  assert.deepEqual(regions, [
    { start: 0, end: 5, source: 0 },
    { start: 6, end: 11, source: 1 },
  ]);
});

test('adjacent spans of the same source merge, across the newline between lines', () => {
  // Sixty thousand segments become a few hundred regions this way, which is
  // what makes the per-occurrence lookup a binary search over a short list.
  const code = 'AAAAA\nBBBBB';
  const { regions } = decodeSourceRegions(code, mapOf(`${line([[0, 0, 0, 0]])};${line([[0, 0, 0, 0]])}`));
  assert.deepEqual(regions, [{ start: 0, end: 11, source: 0 }]);
});

test('a one-field segment ends the span before it and attributes nothing itself', () => {
  // Generated text the map declines to attribute: a bundler runtime helper, a
  // module wrapper. It must not be swallowed into the neighbouring source.
  const code = 'AAAAAHHHHHBBBBB';
  const { regions } = decodeSourceRegions(code, mapOf(line([[0, 0, 0, 0], [5], [10, 1, 0, 0]])));
  assert.deepEqual(regions, [
    { start: 0, end: 5, source: 0 },
    { start: 10, end: 15, source: 1 },
  ]);
  assert.equal(regionSourceAt(regions, 7), -1);
});

// ── THE CAP ─────────────────────────────────────────────────────────────────

test('a span wider than the cap attributes nothing and is reported as coarse', () => {
  const wide = SPAN_ATTRIBUTION_CAP + 1;
  const code = 'x'.repeat(wide) + 'y'.repeat(10);
  const { regions, coarse } = decodeSourceRegions(code, mapOf(line([[0, 0, 0, 0], [wide, 1, 0, 0]])));
  assert.deepEqual(regions, [{ start: wide, end: wide + 10, source: 1 }]);
  assert.deepEqual(coarse, [{ start: 0, end: wide }]);
  assert.equal(regionSourceAt(regions, 5), -1);
  assert.equal(coarseWidthAt(coarse, 5), wide);
});

test('a span exactly at the cap is still attributed', () => {
  // The boundary is stated in the constant's comment as a width in generated
  // characters, so it is a `>` and not a `>=`. Pinned because a silent
  // off-by-one here changes what the measured distribution means.
  const code = 'x'.repeat(SPAN_ATTRIBUTION_CAP);
  const { regions, coarse } = decodeSourceRegions(code, mapOf(line([[0, 0, 0, 0]])));
  assert.deepEqual(regions, [{ start: 0, end: SPAN_ATTRIBUTION_CAP, source: 0 }]);
  assert.deepEqual(coarse, []);
});

test('merging does NOT jump over a span the cap dropped', () => {
  // The subtle one. Two narrow spans of source 0 with an over-cap span of
  // source 0 between them: merging them into one region would put the over-cap
  // text back inside an attributed region and quietly undo the cap.
  const wide = SPAN_ATTRIBUTION_CAP + 1;
  const code = 'a'.repeat(10) + 'x'.repeat(wide) + 'b'.repeat(10);
  const { regions } = decodeSourceRegions(
    code,
    mapOf(line([[0, 0, 0, 0], [10, 0, 0, 0], [10 + wide, 0, 0, 0]])),
  );
  assert.deepEqual(regions, [
    { start: 0, end: 10, source: 0 },
    { start: 10 + wide, end: 20 + wide, source: 0 },
  ]);
  assert.equal(regionSourceAt(regions, 100), -1, 'the dropped middle must not be attributed');
});

// ── REFUSALS: EVERY ONE VOIDS THE WHOLE DECODE ──────────────────────────────

test('an index map is refused rather than mis-decoded', () => {
  const { regions, why } = decodeSourceRegions('abc', {
    version: 3,
    sections: [{ offset: { line: 0, column: 0 }, map: mapOf(line([[0, 0, 0, 0]])) }],
  });
  assert.equal(regions, null);
  assert.match(why, /index map/);
});

test('a map with no mappings, no sources, or no source at all is refused', () => {
  assert.match(decodeSourceRegions('abc', { version: 3, sources: ['a'] }).why, /no "mappings" string/);
  assert.match(decodeSourceRegions('abc', { version: 3, mappings: '' }).why, /no "sources" array/);
  assert.match(decodeSourceRegions('abc', { version: 3, sources: [], mappings: '' }).why, /lists no sources/);
  assert.equal(decodeSourceRegions('abc', null).regions, null);
});

test('a segment with a field count revision 3 does not define is refused', () => {
  for (const fields of [2, 3, 6]) {
    const seg = 'A'.repeat(fields);
    const { regions, why } = decodeSourceRegions('abcdef', mapOf(seg));
    assert.equal(regions, null, `${fields} fields`);
    assert.match(why, new RegExp(`has ${fields} fields`));
  }
});

test('a character that is not base64 VLQ is refused', () => {
  const { regions, why } = decodeSourceRegions('abcdef', mapOf('A!AA'));
  assert.equal(regions, null);
  assert.match(why, /not base64 VLQ/);
});

test('a segment that ends mid-value is refused', () => {
  // `g` has the continuation bit set with nothing after it.
  const { regions, why } = decodeSourceRegions('abcdef', mapOf('AAAg'));
  assert.equal(regions, null);
  assert.match(why, /ends mid-value/);
});

test('a source index outside the sources table is refused', () => {
  const { regions, why } = decodeSourceRegions('abcdef', mapOf(line([[0, 5, 0, 0]])));
  assert.equal(regions, null);
  assert.match(why, /names source 5 of 2/);
});

test('a negative generated column is refused', () => {
  // Reachable through the deltas: a second segment whose column delta takes
  // the running total below zero.
  const { regions, why } = decodeSourceRegions('abcdef', mapOf(`${vlq(2)}AAA,${vlq(-4)}AAA`));
  assert.equal(regions, null);
  assert.match(why, /at generated column -2/);
});

test('an original line past the end of the source it names is refused', () => {
  // The check that catches a map paired with the wrong build: the mapping
  // points at line 40 of a file the same map says is three lines long.
  const { regions, why } = decodeSourceRegions('abcdef', mapOf(line([[0, 0, 40, 0]])));
  assert.equal(regions, null);
  assert.match(why, /points at line 41 of a source that has 3/);
});

test('an original line is NOT range-checked against a source whose text is absent', () => {
  // The check above needs the republished text to work. Where the map omitted
  // it there is nothing to check against, so the check is skipped rather than
  // faked — the alternative is refusing every map that ships `sources` without
  // `sourcesContent`, which is a common and perfectly honest shape.
  const map = { version: 3, sources: ['a.js'], sourcesContent: [null], mappings: line([[0, 0, 40, 0]]) };
  const { regions } = decodeSourceRegions('abcdef', map);
  assert.deepEqual(regions, [{ start: 0, end: 6, source: 0 }]);
});

test('mappings describing more generated lines than the artefact has are refused', () => {
  // A map paired with the wrong artefact. Silently ignoring the overflow would
  // attribute the lines that DO exist and look like a clean decode.
  const { regions, why } = decodeSourceRegions('one line only', mapOf(`${line([[0, 0, 0, 0]])};;;AAAA`));
  assert.equal(regions, null);
  assert.match(why, /describe generated line 4 and the artefact has 1/);
});

test('the segment cap is a refusal, not a truncation', () => {
  // A half-read table would attribute the first half of a file correctly and
  // attribute nothing in the second, which reads exactly like a bundle whose
  // later modules were all minified away.
  //
  // This one builds the two million segments for real rather than asserting
  // the constant, because the constant is not the property. Measured on this
  // machine at 1.35 s and 387 MB RSS at the default heap size — the most
  // expensive test in this package by an order of magnitude, and worth it
  // exactly once.
  const over = `AAAA,`.repeat(MAX_MAPPING_SEGMENTS + 1).slice(0, -1);
  const big = decodeSourceRegions('x'.repeat(10), {
    version: 3,
    sources: ['a.js'],
    sourcesContent: ['x'],
    mappings: over,
  });
  assert.equal(big.regions, null);
  assert.match(big.why, /more than 2000000 segments/);

  // And the guard is only meaningful if the ordinary case sails past it.
  const ordinary = decodeSourceRegions('abcdef', mapOf(line([[0, 0, 0, 0], [3, 1, 0, 0]])));
  assert.notEqual(ordinary.regions, null, ordinary.why);
});

// ── LOOKUPS ─────────────────────────────────────────────────────────────────

test('a region contains its start and not its end', () => {
  const regions = [{ start: 4, end: 8, source: 3 }];
  assert.equal(regionSourceAt(regions, 3), -1);
  assert.equal(regionSourceAt(regions, 4), 3);
  assert.equal(regionSourceAt(regions, 7), 3);
  assert.equal(regionSourceAt(regions, 8), -1);
  assert.equal(regionSourceAt([], 0), -1);
  assert.equal(coarseWidthAt([], 0), 0);
});

test('sourceIndexesCarrying unions every entry that holds the probe, and skips holes', () => {
  // Code splitting duplicates a module across entry points and a barrel
  // republishes it, so several entries legitimately carry the same text. A
  // `null` entry is a source the map named without republishing.
  const probe = 'if (!session.isAdmin) throw new Error("forbidden");';
  assert.deepEqual(sourceIndexesCarrying([`a ${probe} b`, null, 'unrelated', probe], probe), [0, 3]);
  assert.deepEqual(sourceIndexesCarrying(['unrelated'], probe), []);
});

// ── NEWLINES ────────────────────────────────────────────────────────────────

test('CRLF normalisation does not move any column, only the line starts', () => {
  // Map columns are counted from the start of their own generated line, and
  // the `\r` normalisation removes is the last character of a CRLF line — so
  // no column within a line moves. Absolute offsets do, which is why the
  // line-start table is built from the normalised text. Same map, same
  // columns, offsets shifted by one per preceding line.
  const mappings = `${line([[0, 0, 0, 0]])};${line([[0, 1, 0, 0]])}`;
  const lf = decodeSourceRegions('AAAAA\nBBBBB', mapOf(mappings));
  assert.deepEqual(lf.regions, [
    { start: 0, end: 5, source: 0 },
    { start: 6, end: 11, source: 1 },
  ]);
});
